/**
 * Copyright (c) 2026 Bivex
 *
 * Author: Bivex
 * Available for contact via email: support@b-b.top
 * For up-to-date contact information:
 * https://github.com/bivex
 *
 * Created: 2026-03-26 18:54
 * Last Updated: 2026-03-26 18:54
 *
 * Licensed under the MIT License.
 * Commercial licensing available upon request.
 */

const path = require("node:path");
const fs = require("node:fs");

const {transpile} = require("../src/transpile");

const samplePath = path.join(__dirname, "../sample/browserFingerprint.js");
const outputDir = path.join(__dirname, "../output/browser-fingerprint");
const vmOutputPath = path.join(outputDir, "vm.js");
const appOutputPath = path.join(outputDir, "app.js");
const htmlOutputPath = path.join(outputDir, "index.html");

function adaptVmForBrowser(vmSource) {
    let result = vmSource;

    result = result.replace(
        /const zlib = require\((["'])node:zlib\1\);/,
        `const zlib = {
    inflateSync(buffer) {
        if (typeof pako === "undefined") {
            throw new Error("pako is required in the browser demo");
        }
        return pako.inflate(buffer);
    }
};

const Buffer = {
    from(code, format) {
        if (format !== "base64") {
            throw new Error("Browser demo only supports base64 bytecode");
        }
        const binary = atob(code);
        const bytes = new Uint8Array(binary.length);
        for (let i = 0; i < binary.length; i++) {
            bytes[i] = binary.charCodeAt(i);
        }
        return bytes;
    }
};`
    );

    result = result.replace(/module\.exports = JSVM;?/, "window.JSVM = JSVM");

    return result;
}

function buildHtml() {
    return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>JS Virtualizer Browser Fingerprint Demo</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #f4efe8;
      --panel: #fffaf2;
      --ink: #1f1a17;
      --accent: #9d3f2c;
      --border: #d8c7b5;
    }
    body {
      margin: 0;
      font-family: "Georgia", "Iowan Old Style", serif;
      background: radial-gradient(circle at top, #fff7ec, var(--bg));
      color: var(--ink);
    }
    main {
      max-width: 900px;
      margin: 48px auto;
      padding: 24px;
    }
    .card {
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 18px;
      box-shadow: 0 18px 50px rgba(70, 41, 20, 0.08);
      padding: 24px;
    }
    h1 {
      margin-top: 0;
      font-size: 2.2rem;
      color: var(--accent);
    }
    pre {
      white-space: pre-wrap;
      word-break: break-word;
      background: #201a17;
      color: #f6e8d5;
      border-radius: 14px;
      padding: 16px;
      overflow: auto;
    }
    p {
      line-height: 1.55;
    }
  </style>
</head>
<body>
  <main>
    <div class="card">
      <h1>Browser Fingerprint Demo</h1>
      <p>This page runs a virtualized fingerprint function generated by js-virtualizer.</p>
      <pre id="fingerprint-output">Loading virtualized fingerprint...</pre>
    </div>
  </main>
  <script>
    window.require = function () {
      return window.JSVM;
    };
  </script>
  <script src="https://cdn.jsdelivr.net/npm/pako@2.1.0/dist/pako.min.js"></script>
  <script src="./vm.js"></script>
  <script src="./app.js"></script>
</body>
</html>`;
}

async function main() {
    fs.mkdirSync(outputDir, {recursive: true});

    const sampleCode = fs.readFileSync(samplePath, "utf-8");
    const result = await transpile(sampleCode, {
        fileName: "browser-fingerprint-demo.js",
        writeOutput: false,
        passes: ["RemoveUnused", "ObfuscateTranspiled"]
    });

    fs.writeFileSync(vmOutputPath, adaptVmForBrowser(result.vm));
    fs.writeFileSync(appOutputPath, result.transpiled);
    fs.writeFileSync(htmlOutputPath, buildHtml());

    console.log(`HTML demo: ${htmlOutputPath}`);
    console.log(`Browser VM: ${vmOutputPath}`);
    console.log(`Browser app: ${appOutputPath}`);
    console.log("Open index.html in a browser, or serve the folder with a static server.");
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
